### ISSUE TITLE
IONIC 3: Exception loading config file ADBMobileConfig.json

### ISSUE THREAD

**Issue by zakariajmili** [Adobe-Marketing-Cloud/mobile-services#224] opened 2017-09-11 08:52 UTC
Hi,

I want integrate the plugin ADBMobile on IONIC 3 project, but I have the error:

ADBMobile: ADBMobile Error : Config - Exception loading config file (ADBMobileConfig.json)

Can you help me please

**Comment by sbenedicadb** [comment] 2017-09-11 14:59
Hey @zakariajmili,

The error message you are seeing is likely caused by the SDK being unable to find your `ADBMobileConfig.json` file.  

- For iOS, you'll need to make sure that the config file is included in your target's bundle.  
- For Android, make sure that the config file is in your app's `assets` directory.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by zakariajmili** [comment] 2017-09-11 15:14
thank you for your reply

But in cordova sdk documentation , it's advisable to put the config file in the www folder.

P.S: I put config file in  app's assets directory but not work

**Comment by shalehaha** [comment] 2017-11-17 21:16
@zakariajmili,

Have you figured it out? If not, could you please provide the full log, and it'd be super helpful if you can give us a sample app which could reproduce the issue you are seeing.

SDK does look for the config file from the www folder, so if you put it there, I believe it should work.

**Comment by shalehaha** [comment] 2018-02-02 17:15
Closing the ticket, feel free to reopen it if needed.

**Closed by shalehaha** 2018-02-02 17:15 UTC

**Comment by PfizerAnshul** [comment] 2019-04-19 10:51
HI All ,
i am working on integrating Adobe analytics with cordova android app and according to document i have put my ADBMobileConfig.json file in assets/www/ ,after creating apk and  checking logs with adb logcat i am getting ADBMobile: ADBMobile Error : Config - Exception loading config file (ADBMobileConfig.json) error.
i have also unzipped my .apk file and unable to find ADBMobileConfig.json in asset folder .
can some one please help?
