### ISSUE TITLE
Failed to open database 'ADBMobileDataCache.sqlite'

### ISSUE THREAD

**Issue by test-adobe** [Adobe-Marketing-Cloud/mobile-services#242] opened 2017-11-22 01:02 UTC
After an Android app crash, no image requests are being sent even after the app is restarted.
 
Based on the log below, it seems the issue is on the ADBMobileDataCache.sqlite.
 
11-20 16:00:32.777 14318-14391/com.clearchannel.iheartradio.controller E/SQLiteDatabase: Failed to open database 'ADBMobileDataCache.sqlite'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
at com.adobe.mobile.AbstractDatabaseBacking.openOrCreateDatabase(AbstractDatabaseBacking.java:59)
at com.adobe.mobile.AbstractDatabaseBacking.initDatabaseBacking(AbstractDatabaseBacking.java:82)
at com.adobe.mobile.AnalyticsWorker.<init>(AnalyticsWorker.java:77)
at com.adobe.mobile.AnalyticsWorker.sharedInstance(AnalyticsWorker.java:64)
at com.adobe.mobile.RequestBuilder.buildAndSendRequest(RequestBuilder.java:126)
at com.adobe.mobile.AnalyticsTrackState.trackState(AnalyticsTrackState.java:30)
at com.adobe.mobile.Analytics$1.run(Analytics.java:71)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
11-20 16:00:32.781 14318-14318/com.clearchannel.iheartradio.controller D/AdobeConfig: beginDataCollection

Any reason as to why the error might throw up only when the app is restarted after a crash?

**Comment by sbenedicadb** [comment] 2017-11-27 19:37
Hey @test-adobe,

Error code 14 for SQLite means that we were unable to open the database.  If the failure occurs after a crash, it seems reasonable that there may have been a lock on the DB that didn't get cleared.  I believe this is an issue that we fixed in SDK version `4.13.3`.  What version of the SDK are you on?  Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by test-adobe** [comment] 2017-11-28 16:47
Hi Steve,

The SDK being used is version 4.13.7 (adobeMobileLibrary-4.13.7.jar). Should this still be occurring given we are at a later version than 4.13.3? 

What other details could I provide to help troubleshoot on this issue? 

Best,
Harsha

**Comment by shalehaha** [comment] 2017-11-28 21:45
@test-adobe,

Are you still able to reproduce this issue? Can you give us the full log since the app launch? And if you reboot the device, does the error still happen?

This error would happen when SDK fails to open the db file and even fails to delete it, normally it is caused by the file being locked or the permission of the file or the cache directory has changed. And once it runs into this situation, actually there is nothing SDK can do to recover. 

The fix we did on 4.13.3 was just to provide better log and bail out early when we detect a fatal error on db.

**Comment by shalehaha** [comment] 2017-12-11 21:51
Closing this ticket, the issue has been reported through client care.

**Closed by shalehaha** 2017-12-11 21:51 UTC
