### ISSUE TITLE
AnalyticsWorker Crash in android. 

### ISSUE THREAD

**Issue by Rajarose89** [Adobe-Marketing-Cloud/mobile-services#219] opened 2017-08-18 05:36 UTC
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.adobe.mobile.AbstractHitDatabase$Hit.identifier' on a null object reference
	at com.adobe.mobile.AnalyticsWorker$1.run(AnalyticsWorker.java:337)
	at java.lang.Thread.run(Thread.java:820)

**Comment by shalehaha** [comment] 2017-08-22 17:17
@Rajarose89,

How frequently are you running into this exception? Are you able to reproduce it in a consistent way? And which version of SDK are you on?

This is an extremely weird bug, we have null check for the Hit object, so there shouldn't be any NullPointerException thrown because of it. To help us investigate this issue, any additional info would be helpful.

Jiabin

**Comment by rajarose** [comment] 2017-08-24 05:41
@shalehaha I think the problem is was used google analytics in same project. When after i remove google analytics , adobe crash not happened!! But it is major problem why it happened in your library? Adobe jar version - adobeMobileLibrary-4.13.7 .

**Comment by shalehaha** [comment] 2017-11-17 21:36
@rajarose,

Closing this one since it's not related to Adobe's SDK. I guess it's might because google analytics is using reflection or other technologies, which happen to cause conflicts with Adobe's SDK. But feel free to reopen it if you need further help. Thanks.

**Closed by shalehaha** 2017-11-17 21:36 UTC
