### ISSUE TITLE
Calling userIdentifier or trackingIdentifier hangs on iOS SDK when app enters foreground after tracking an action on a launch from background.

### ISSUE THREAD

**Issue by HardipAtWpost** [Adobe-Marketing-Cloud/mobile-services#167] opened 2016-08-06 22:24 UTC
Our app uses interactive push notifications on iOS.  The user of the app has the option of reading an article or saving it from notification center.  If the user selects the Save option while the app is in a cold state, the app will launch in the background and save the the article data and then it makes a trackAction (or trackActionFromBackground) call to Omniture to track this user event.  The app never enters the foreground in this case.  

The next time the user launches the app and the app goes from background state to foreground state, if calls are made to ADBMobile.userIdentifier or ADBMobile.trackingIdentifier, the calls just hang.  If this call is made on the main thread, the call locks up the main thread and the app crashes.  We originally saw this on version 4.8.6, but the same behavior was seen when upgrading to the latest version of the SDK (4.11.1)

```
Aug  6 18:19:28 Nightcrawler amfid[2183] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Aug  6 18:19:28 Nightcrawler com.apple.xpc.launchd[1] <Error>: assertion failed: 13G34: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: [Crashlytics] Version 3.4.1 (92)
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: -[WPAppDelegate application:didFinishLaunchingWithOptions:] line 197 $ Application starts
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Config - Attempting to load config file from /var/containers/Bundle/Application/B6663C0F-12F7-4A83-B2F2-4C4DAD1ADF6C/Classic.app/ADBMobileConfigDebug.json
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Config - Loaded 7 root elements
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Warning: Config - "clientCode" is required for Target configuration
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Warning: Config - "server" is required for Audience Manager configuration
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Warning: Config - "appid" is required for Acquisition configuration
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Warning: Config - "server" is required for Acquisition configuration
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Messages - Attempting to load bundled In-App Messages.
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Messages - Attempting to load cached In-App Messages.
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Cached Files - No URL for cached file.
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Messages - No Messages to load.
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Config - Attempting to load cached POI data.
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Cached Files - No URL for cached file.
Aug  6 18:19:29 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Config - No remote POI's available
Aug  6 18:19:30 Nightcrawler Classic[2300] <Warning>: ADBMobile Debug: Analytics - App start detected but suppressing lifecycle hit because the application is in the background
Aug  6 18:20:18 Nightcrawler Classic[2300] <Warning>: [Crashlytics:Crash] Warning: NSUncaughtExceptionHandler is 'GADHandleUncaughtException' in '/var/containers/Bundle/Application/B6663C0F-12F7-4A83-B2F2-4C4DAD1ADF6C/Classic.app/Classic'
Aug  6 18:20:18 Nightcrawler Classic[2300] <Warning>: -[WPAppDelegate applicationWillEnterForeground:] line 377 $ Application will enter foreground
Aug  6 18:20:19 Nightcrawler nehelper[2178] <Error>: Configuration for provider com.apple.NetworkExtension.NetworkServiceProxy does not exist (<__NSConcreteUUID 0x15fe07fe0> 4EDA3C35-A20F-4E5E-BF90-6E9A6F8D3EBD) or is not enabled (0)
Aug  6 18:20:19 Nightcrawler UserEventAgent[26] <Error>: Probe message failed
Aug  6 18:20:28 Nightcrawler timed[70] <Notice>: (Error) TimeLink: E4E72EC7-109A-424B-A037-02E42059BA01 (12) send failure (Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x13e633720 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}), will retry
Aug  6 18:20:28 Nightcrawler timed[70] <Notice>: (Error) TimeLink: 83468AD4-FF21-4E1B-8FD3-74B1F94A4DB6 (7) send failure (Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x13e53a170 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}), will retry
Aug  6 18:20:28 Nightcrawler timed[70] <Notice>: (Error) TimeLink: DEF4C424-D90B-4F93-B43D-65AE4AAB10CF (4-TMLSSourceDevice) send failure (Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x13e628240 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}), will retry
Aug  6 18:20:28 Nightcrawler SpringBoard[63] <Warning>: Forcing crash report of <FBApplicationProcess: 0x12ffde450; Classic; pid: 2300> (reason: 1, description: com.pointabout.washingtonpost failed to scene-update after 10.00s)
Aug  6 18:20:28 Nightcrawler diagnosticd[2154] <Error>: unable to find offset 0x8382398c in shared cache for arch 'arm64'
Aug  6 18:20:28 Nightcrawler diagnosticd[2154] <Error>: unable to find offset 0x83a25da8 in shared cache for arch 'arm64'
Aug  6 18:20:28 Nightcrawler diagnosticd[2154] <Error>: Invalid offset 2208456104 into shared cache for arch 'arm64'
Aug  6 18:20:28 Nightcrawler SpringBoard[63] <Warning>: Finished crash reporting.
Aug  6 18:20:28 Nightcrawler com.apple.xpc.launchd[1] (UIKitApplication:com.pointabout.washingtonpost[0x804b][2300]) <Notice>: Service exited due to signal: Killed: 9
Aug  6 18:20:28 Nightcrawler SpringBoard[63] <Warning>: Application 'UIKitApplication:com.pointabout.washingtonpost[0x804b]' exited abnormally via signal.
Aug  6 18:20:28 Nightcrawler backboardd[67] <Warning>: Unable to bootstrap_look_up port with name com.pointabout.washingtonpost.gsEvents: unknown error code (1102)
Aug  6 18:20:29 Nightcrawler UserEventAgent[26] <Warning>: 1937764972489: id=com.pointabout.washingtonpost pid=2300, state=0
Aug  6 18:20:29 Nightcrawler ReportCrash[2301] <Warning>: Saved type '109(109_Classic)' report (3 of max 25) at /var/mobile/Library/Logs/CrashReporter/Classic-2016-08-06-182029.ips
```

```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x0000000183931014 semaphore_wait_trap + 8
1   libsystem_platform.dylib      	0x0000000183a0e97c _os_semaphore_wait + 24
2   libdispatch.dylib             	0x0000000183808378 _dispatch_barrier_sync_f_slow + 560
3   AdobeMobileSDK                	0x0000000100b0c608 0x100afc000 + 67080
4   Classic                       	0x00000001000d4510 +[WPOmniture retrieveVisitorIdentification] (WPOmniture.m:149)
5   Classic                       	0x00000001000d4444 +[WPOmniture trackApplicationLaunch] (WPOmniture.m:144)
6   Classic                       	0x0000000100065110 -[WPAppDelegate initializeViewsAndTrackAppLaunch] (WPAppDelegate.m:76)
7   Classic                       	0x00000001000695d0 -[WPAppDelegate applicationWillEnterForeground:] (WPAppDelegate.m:382)
8   UIKit                         	0x0000000189195468 -[UIApplication _sendWillEnterForegroundCallbacks] + 196
9   UIKit                         	0x00000001891d0578 -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 2176
10  UIKit                         	0x00000001891cfa80 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 448
11  UIKit                         	0x00000001891b970c __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 152
12  UIKit                         	0x00000001891b9394 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 712
13  FrontBoardServices            	0x00000001857537ac __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
14  FrontBoardServices            	0x0000000185753618 -[FBSSerialQueue _performNext] + 168
15  FrontBoardServices            	0x00000001857539c8 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
16  CoreFoundation                	0x0000000183d6909c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
17  CoreFoundation                	0x0000000183d68ab0 __CFRunLoopDoSources0 + 412
18  CoreFoundation                	0x0000000183d66830 __CFRunLoopRun + 724
19  CoreFoundation                	0x0000000183c90c50 CFRunLoopRunSpecific + 384
20  GraphicsServices              	0x0000000185578088 GSEventRunModal + 180
21  UIKit                         	0x0000000188f7a088 UIApplicationMain + 204
22  Classic                       	0x0000000100064cc8 main (main.m:14)
23  libdyld.dylib                 	0x000000018382e8b8 start + 4
```

**Comment by HardipAtWpost** [comment] 2016-08-06 23:01
Additional note: If I make the call in a background queue, not only does it prevent the crash, but the data is returned right away.  I'm not sure why this doesn't work when called on main queue.

**Comment by sbenedicadb** [comment] 2016-08-08 14:42
Hey @HardipAtWpost,

Thanks for the note.  We will look into reproducing and resolving this issue.

-steveb

**Comment by sbenedicadb** [comment] 2016-08-08 23:24
Hey @HardipAtWpost, 

Can you please contact [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket.  I'd like to get more information from you so we can better debug this issue.  Thanks.

-steveb

**Comment by HardipAtWpost** [comment] 2016-08-08 23:26
@sbenedicadb - Sure.  I will do that shortly

**Comment by alcazes** [comment] 2016-08-22 06:48
Hi @HardipAtWpost ,

I am Adobe Lead Technical Support Engineer. For the specific issue an incident needs to be created. I have checked in our system and I cannot see any incident created under your email hardip.singh@washpost.com (it is yours correct ? ). You are not set up as a supported user so if you have sent a incident, it would have been bounced back... 

Could you please let me know if it is the correct email and who is your supported user in your company and I will create an incident so you can provide further details like code to reproduce etc... 

Best regards.

Alexis Cazes.

Lead Technical Support Engineer

**Comment by alcazes** [comment] 2016-09-07 06:01
Hi @HardipAtWpost,

It has been 16 days since my last email and no update was provided.

Please confirm the following: 

- You email is hardip.singh@washpost.com 
- You company is Washington Post Newsweek Interactive

I need these details to be able to create an incident.

Best regards.

Alexis Cazes.

Lead Technical Support Engineer

**Comment by pfransenadb** [comment] 2016-09-07 16:53
Closing this issue.

@HardipAtWpost, please contact client care for further assistance.

-pete

**Closed by pfransenadb** 2016-09-07 16:53 UTC
