### ISSUE TITLE
iOS - CoreTelephony crash on app start (32-bit, iOS 10)

### ISSUE THREAD

**Issue by Bartlomiej-Lupinski** [Adobe-Marketing-Cloud/mobile-services#330] opened 2019-07-23 14:40 UTC
After upgrading from 4.18.5 to 4.18.6 our app now crashes on launch on iPhone 5 with iOS 10.3.3 (unfortunately this is the only device we have with iOS 10 and that is 32-bit, so I can't check if it's due to OS or being 32-bit). Seems to be CoreTelephony related. Here are the crash details:

Date/Time:           2019-07-23 10:36:35.4297 +0200
Launch Time:         2019-07-23 10:36:32.0000 +0200
OS Version:          iPhone OS 10.3.3 (14G60)
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   CoreFoundation                	0x1dd15e90 CFStringCompare + 12
1   CoreTelephony                 	0x20417498 sCTEventForNotificationString+ 25752 (__CFString const*) + 44
2   CoreTelephony                 	0x20453600 _CTServerConnectionRegisterForNotification + 18
3   CoreTelephony                 	0x2043c240 -[CTTelephonyNetworkInfo setUpServerConnection] + 196
4   CoreTelephony                 	0x2043c4b8 -[CTTelephonyNetworkInfo init] + 268
5   AdobeMobileSDK                	0x02048abe 0x2023000 + 154302
6   libdispatch.dylib             	0x1d4ca252 dispatch_once_f + 42
7   AdobeMobileSDK                	0x02048a7e 0x2023000 + 154238
8   dyld                          	0x01ec9dc4 ImageLoaderMachO::doModInitFunctions+ 77252 (ImageLoader::LinkContext const&) + 296
9   dyld                          	0x01ec9f40 ImageLoaderMachO::doInitialization+ 77632 (ImageLoader::LinkContext const&) + 20
10  dyld                          	0x01ec655a ImageLoader::recursiveInitialization+ 62810 (ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 366
11  dyld                          	0x01ec64f4 ImageLoader::recursiveInitialization+ 62708 (ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 264
12  dyld                          	0x01ec5692 ImageLoader::processInitializers+ 59026 (ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 106
13  dyld                          	0x01ec5716 ImageLoader::runInitializers+ 59158 (ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 52
14  dyld                          	0x01eb8fa6 dyld::initializeMainExecutable+ 8102 () + 168
15  dyld                          	0x01ebd152 dyld::_main+ 24914 (macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 3934
16  dyld                          	0x01eb81d0 dyldbootstrap::start+ 4560 (macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 324
17  dyld                          	0x01eb8040 _dyld_start + 64

**Comment by sbenedicadb** [comment] 2019-07-23 19:37
Hey @Bartlomiej-Lupinski,

We have attempted to reproduce this issue using an iPhone 5 running iOS 10.3.4, but we haven't had any success.  Are there steps that you know of that can cause this crash reliably?

Thanks.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by Bartlomiej-Lupinski** [comment] 2019-07-24 12:37
It was a guaranteed crash for us every time, maybe the CoreTelephony needs to be linked to the app.

**Comment by Bartlomiej-Lupinski** [comment] 2019-07-24 12:55
Quick update: we received more crash reports and it also happens on iPhone 6 and 6S, as long as they have iOS 10 installed. Also occurs on devices with iOS 9

**Comment by jiabingeng** [comment] 2019-07-24 17:30
@Bartlomiej-Lupinski 

Do you have the crash rate for iOS 9/10?

We guess it might because there is another library in your app relying on CoreTelephony. Is it possible for you to provide us the list of the 3rd party libraries that are included in the app? And also check whether your source code is calling to CoreTelephony?

Thanks,
Jiabin

**Comment by Bartlomiej-Lupinski** [comment] 2019-07-24 23:18
@jiabingeng 
From the information I have, the crash rate seems to be 100% on affected devices. Among 3rd party libraries only PhoneNumberKit uses CoreTelephony and we're planning to edit it and remove CoreTelephony dependency from it in hope to have an alternate solution to this problem (right now it's downgrading AdobeMobileSDK to 4.18.5).
Our own code is never calling CoreTelephony though, so we're not really dependent on it.

**Comment by shalehaha** [comment] 2019-07-26 15:45
@Bartlomiej-Lupinski 
Thanks for the info and we were able to reproduce the crash. If the SDK was imported as a framework and CoreTelephony.framework was also being linked to the app, then it will crash on iOS 9/10 devices or simulators. 
We are planning to roll out a hotfix soon.

Jiabin

**Comment by shalehaha** [comment] 2019-08-06 15:16
@Bartlomiej-Lupinski 
This problem has been fixed in version 4.18.7 which was released last week, please give it a try and let us know the result. 

Thanks,
Jiabin

**Closed by shalehaha** 2019-08-06 15:16 UTC

**Comment by Bartlomiej-Lupinski** [comment] 2019-09-27 16:07
Sorry for late reply, but I checked it and can confirm the crash is fixed.

**Comment by shalehaha** [comment] 2019-09-27 16:10
@Bartlomiej-Lupinski thanks.
