### ISSUE TITLE
iOS v4.5.5 doesn't compile for archive builds

### ISSUE THREAD

**Issue by acorscadden** [Adobe-Marketing-Cloud/mobile-services#79] opened 2015-08-31 16:55 UTC
AdobeMobileSDK v4.5.5 doesn't compile for achieve builds due to a bunch of these duplicate symbol errors:
```
duplicate symbol _llvm.cmdline in:
    /Users/adriancorscadden/code/Phoenix/Phoenix/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherExists.o)
    /Users/adriancorscadden/code/Phoenix/Phoenix/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherNotExists.o)
duplicate symbol _llvm.embedded.module in:
    /Users/adriancorscadden/code/Phoenix/Phoenix/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherExists.o)
    /Users/adriancorscadden/code/Phoenix/Phoenix/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherNotExists.o)
duplicate symbol _llvm.cmdline in:
    /Users/adriancorscadden/code/Phoenix/Phoenix/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherExists.o)
    /Users/adriancorscadden/code/Phoenix/Phoenix/Pods/AdobeMobileSDK/AdobeMobileLibrary/libAdobeMobile.a(ADBMessageMatcherStartsWith.o)
```

**Comment by acorscadden** [comment] 2015-08-31 17:00
Reverting to 4.5.4 fixes this. I should also note that I'm using Xcode 6.4

**Comment by xfreebird** [comment] 2015-08-31 17:02
Recently they have enabled bitcode "app thinning", and the error you see is because you're using Xcode < 7.

Bitcode enabled binaries work only only on Xcode 7+.

Try using the previous version of the library, it doesn't have bitcode enabled.
Or switch to Xcode 7

**Comment by acorscadden** [comment] 2015-08-31 17:11
Ok, thanks :)

**Comment by shalehaha** [comment] 2015-09-03 16:21
@acorscadden, we can see the similar errors when running an app on simulator with Xcode 6.4, and this will be fixed in our next release. But we couldn't reproduce it when archiving the app.
Do you mind give us a little more details about how to replicate it and it'd better if you can provide us the full error logs in Xcode.
Thanks,
-Jiabin

**Comment by vinnybad** [comment] 2015-09-03 17:10
@shalehaha  I'm seeing this on v4.5.6 but not on v4.5.5.  

ld: 94 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The pod is specified only once in our main target.  The tests target depends on the main target.  

Reverting to v4.5.5 on Xcode 6.4 seems to not reproduce the error again.

**Comment by shalehaha** [comment] 2015-09-03 17:50
@vinnybad thanks for you feedback, we are still working on fixing all the bitcode related compile issues.

**Comment by shalehaha** [comment] 2015-09-03 17:52
@acorscadden one more follow up question, could you check the build settings of your app, is 'Dead Code Stripping' set to NO?
-Jiabin

**Closed** 2015-10-22 20:41 UTC
