### ISSUE TITLE
ADBMobile.visitorAppend(to:) not extending URL right after startup

### ISSUE THREAD

**Issue by dklein42** [Adobe-Marketing-Cloud/mobile-services#274] opened 2018-04-11 21:27 UTC
Hi,

our iOS app has to load an embedded web page on the first screen right after startup and for this has to use `ADBMobile.visitorAppend(to:)` to transfer the visitor identifier. While we do not see problems with `ADBMobile.visitorAppend(to:)` later into the runtime of the app, we quite often (but not always) see `ADBMobile.visitorAppend(to:)` **not** extending the visitor ID for that first call.

I guess this has to do with the method returning before the network call retrieving that info is finished. The documentation says that the method call blocks for a maximum of 100 ms, but it doesn't say how to handle cases where that time was not enough.

Interestingly, the same seems to happen when the device is offline. So if the visitor identifier is retained from previous sessions, why don't you always return the cached version while you are still updating the identifier?

How are we supposed to handle this properly?

Regards,

Daniel

**Comment by shalehaha** [comment] 2018-04-11 23:10
@dklein42,

I couldn't reproduce this issue and also checked the code path in SDK, looks like this scenario should never happen. The 'ADBMobile.visitorAppend(to:)' call is blocked until the SDK has finished reading it from either NSUserDefault or the server.

Which version of SDK are you on?
Are you able to reproduce it quite consistently? If so, can you enable the debug logging of SDK and then send us the full log?

Thanks,

**Jiabin Geng**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by dklein42** [comment] 2018-04-13 14:57
Hi @shalehaha,

thanks for checking this.

My SDK version is 4.15.0 (should be the latest). Yes, I can reproduce this consistently. [Here](https://github.com/Adobe-Marketing-Cloud/mobile-services/files/1907845/Adobe.URL.Extension.Problem.Debug.Output.txt) is my debug log.

Please let me know if I can help you further.

Regards,

Daniel

**Comment by shalehaha** [comment] 2018-04-13 20:46
@dklein42,

Thanks for the log, it is super helpful. So right after the app launch SDK automatically sends a sync request to visitor id service, and if the method `ADBMobile.visitorAppend(to:)` is called at the same time, it may fail if the visitor id sync request takes more than 100ms.

I will file an internal bug to address this issue, but it seems pretty edge case to us and I'm not sure whether or when we will fix it.

But here is a workaround we can think of:
Calling `[ADBMobile visitorMarketingCloudID]` before `ADBMobile.visitorAppend(to:)`, `[ADBMobile visitorMarketingCloudID]` is a blocking sync call, so this method will only return after the visitor id sync request is finished. This works for both the first launch and subsequent launches, can make sure get ids appended always. But since it's a sync call and can block the UI thread, so you'd better put the code onto a background thread.
```
[ADBMobile visitorMarketingCloudID];
id url = [ADBMobile visitorAppendToURL:[NSURL URLWithString:@"https://url"]];
```

Let me know whether it helps.

**Comment by dklein42** [comment] 2018-04-19 08:43
@shalehaha,

I didn't want to _always_ call `visitorMarketingCloudID`, and due to the fact when I recognize that my URL has not been extended the network call is already under way anyway, I implemented a polling mechanism that waits for the call to finish and hence `ADBMobile.visitorAppend(to:)` to start working. In tests it was working fine and without significant delays, which would be OK for us.

Even if this is a corner case for you, I would recommend to change the behavior of `ADBMobile.visitorAppend(to:)` in case of a timeout. Always returning the cached visitor ID, which I would get anyway when there is a connectivity issue, would be appreciated and would match the developers' expectations after reading the documentation.

Thanks for your support!

-Daniel

**Comment by emdobrin** [comment] 2019-08-14 21:43
Hi @dklein42 ,

Mobile SDK has a new asynchronous API since v4.16.0 `Visitor.getUrlVariablesAsync` that can help with your use case, find more about this here: [Adobe Experience Platform Identity Service methods](https://docs.adobe.com/content/help/en/mobile-services/android/experience-cloud-android/mc-methods.html). 

Thanks,
Emilia Dobrin
Computer Scientist
[Adobe Experience Cloud ](https://www.adobe.com/experience-cloud.html)

**Comment by emdobrin** [comment] 2019-08-14 21:44
Closing this issue now.

**Closed by emdobrin** 2019-08-14 21:44 UTC
