### ISSUE TITLE
Rejecting class FloatingButton (Android 5)

### ISSUE THREAD

**Issue by niclashalvorsen** [Adobe-Marketing-Cloud/mobile-services#376] opened 2020-08-19 08:33 UTC
Hi,

We suddenly started getting this error on Android 5 devices and have not changed anything related to Adobe in our code.
Is this a known issue?

```
Fatal Exception: java.lang.VerifyError
Rejecting class com.adobe.mobile.FloatingButton because it failed compile-time verification (declaration of 'com.adobe.mobile.FloatingButton' appears in /data/app/.../base.apk:classes4.dex)
com.adobe.mobile.TargetPreviewManager.setupPreviewButton (TargetPreviewManager.java:251)
com.adobe.mobile.Lifecycle.start (Lifecycle.java:129)
com.adobe.mobile.Config$10.run (Config.java:260)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:818)

```
Version in use: com.adobe.mobile:adobeMobileLibrary:4.18.1

**Comment by niclashalvorsen** [comment] 2020-08-19 11:56
Seems like its related to Gradle version com.android.tools.build:gradle:4.0.0

**Comment by rymorale** [comment] 2020-08-19 15:13
Thanks for the info @niclashalvorsen. I'll investigate this issue and let you know if we have any information.

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by rymorale** [comment] 2020-08-19 17:00
Hi @niclashalvorsen, I'm unable to reproduce the issue on an Android 5.0 device with the same gradle and adobe sdk version. I have a couple questions to help narrow down the issue.
1. Did the issue start occurring after updating the Adobe SDK? 
2. You also mention it occurs on Android 5.0 devices. Does it occur on all Android 5.0 devices or only some of them?
3. This question is related to question 1. Does your app use Target Preview? If so, was it working before you updated the Adobe SDK?

Thanks,
Ryan

**Comment by niclashalvorsen** [comment] 2020-08-20 09:26
Hi, so the issue is not related to Gradle after all, it's related to an update of our proprietary third party security sdk.
But it's still a bit strange that it only affects `com.adobe.mobile.FloatingButton` and nothing else in the app.

1. Did not update the Adobe SDK.
2. It crashes for all Android 5 devices when calling `Config.collectLifecycleData(activity)`.
3. ^ 

I will pass the issue to our third party security provider. So i guess you can close this thread.

Thanks!

**Comment by rymorale** [comment] 2020-08-20 14:06
Thanks for the update @niclashalvorsen. Closing this issue.

**Closed by rymorale** 2020-08-20 14:06 UTC
